# Generated by Django 6.1.1 on 2026-09-02 18:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='CatalogoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Servicio',
                'verbose_name_plural': 'Catálogo de Servicios',
            },
        ),
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delegación',
                'verbose_name_plural': 'Delegaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Trimestre 3 - 2026', max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('dias_computables', models.IntegerField(default=90)),
                ('cerrado', models.BooleanField(default=False)),
                ('umbral_colectivo', models.FloatField(default=80.0, help_text='Umbral mínimo colectivo (%)')),
                ('tope_cumplimiento', models.FloatField(default=150.0, help_text='Tope máximo de cumplimiento (%)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Período de Medición',
                'verbose_name_plural': 'Períodos de Medición',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDINADOR', 'Coordinador Comunal'), ('DELEGADO', 'Delegado Municipal'), ('FUNCIONARIO', 'Funcionario de Terreno')], default='FUNCIONARIO', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('rut_anonimizado', models.CharField(blank=True, max_length=20, null=True)),
                ('totp_secret', models.CharField(blank=True, help_text='Preparado para 2FA', max_length=64, null=True)),
                ('requires_2fa', models.BooleanField(default=False)),
                ('is_2fa_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='sgr_app.cargo')),
                ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='sgr_app.delegacion')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompromisoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(help_text='Nombre anonimizado de vecino u organización', max_length=150)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_comprometida', models.DateField()),
                ('area_apoyo', models.CharField(blank=True, help_text='Área interna de apoyo', max_length=100, null=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('REALIZADO', 'Realizado')], default='EN_PROCESO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisos_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos_asignados', to=settings.AUTH_USER_MODEL)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='sgr_app.delegacion')),
            ],
            options={
                'verbose_name': 'Compromiso de Agenda',
                'verbose_name_plural': 'Compromisos de Agenda',
                'ordering': ['fecha_comprometida'],
            },
        ),
        migrations.CreateModel(
            name='CasoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_caso', models.CharField(max_length=30, unique=True)),
                ('persona_anonimizada', models.CharField(max_length=150)),
                ('fecha_apertura', models.DateField(default=django.utils.timezone.now)),
                ('cerrado', models.BooleanField(default=False)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_sociales', to='sgr_app.delegacion')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora generada por el servidor')),
                ('fecha_actividad', models.DateField(default=django.utils.timezone.now, help_text='Fecha de realización')),
                ('actividad_solicitud', models.CharField(help_text='Problema atendido o solicitud', max_length=255)),
                ('accion_ejecutada', models.TextField(help_text='Acción desarrollada')),
                ('contacto_nombre', models.CharField(blank=True, help_text='Nombre de referencia anonimizado', max_length=150, null=True)),
                ('contacto_telefono', models.CharField(blank=True, help_text='Teléfono anonimizado', max_length=50, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
                ('catalogo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='sgr_app.catalogoservicio')),
                ('compromiso_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_derivadas', to='sgr_app.compromisoagenda')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='sgr_app.delegacion')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificador', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('archivo_foto', models.ImageField(blank=True, null=True, upload_to='evidencias/%Y/%m/')),
                ('url_foto_simulada', models.URLField(blank=True, max_length=500, null=True)),
                ('hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Validación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CORRECCION', 'Requiere Corrección')], default='PENDIENTE', max_length=20)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidencia', to='sgr_app.actividad')),
                ('verificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia Fotográfica',
                'verbose_name_plural': 'Evidencias Fotográficas',
            },
        ),
        migrations.CreateModel(
            name='ItemMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_item', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('meta_cuantitativa', models.FloatField(default=1.0, help_text='Meta esperada en el período (>0)')),
                ('ponderador', models.FloatField(default=25.0, help_text='Porcentaje de peso ponderado (0 a 100)')),
                ('unidad_medida', models.CharField(default='Actividades', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_medicion', to='sgr_app.cargo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_medicion', to='sgr_app.periodomedicion')),
            ],
            options={
                'verbose_name': 'Ítem de Medición',
                'verbose_name_plural': 'Ítems de Medición',
                'unique_together': {('cargo', 'periodo', 'nombre_item')},
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='item_medicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='sgr_app.itemmedicion'),
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('entidad', models.CharField(max_length=50)),
                ('identificador_registro', models.CharField(max_length=50)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AtencionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.PositiveSmallIntegerField(choices=[(1, 'Primera Gestión / Diagnóstico'), (2, 'Segunda Gestión / Seguimiento'), (3, 'Tercera Gestión / Cierre o Derivación')])),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo_atencion', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('resultado', models.CharField(max_length=150)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='sgr_app.casosocial')),
            ],
            options={
                'ordering': ['caso', 'etapa'],
                'unique_together': {('caso', 'etapa')},
            },
        ),
    ]
